services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=feed_db
    ports:
      - "15432:5432"
